### ISSUE TITLE
Can't compile with ghc 7.10.1

### ISSUE THREAD

**Issue by the-drunk-coder** [ninegua/CCA#4]
Just tried to install CCA (as part of Euterpea), without success. Seems to be a problem with Template Haskell, which has reportedly changed, but i'm not expert enough to pinpoint it, really ... here's what it says (no matter if from hackage or from source):

```
Preprocessing library CCA-0.1.5.2...
[1 of 4] Compiling Language.Haskell.TH.Instances ( src/Language/Haskell/TH/Instances.hs, dist/build/Language/Haskell/TH/Instances.o )

src/Language/Haskell/TH/Instances.hs:48:9:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH.Syntax),
      ‘ClassI’ (imported from Language.Haskell.TH.Syntax),
      ‘Clause’ (imported from Language.Haskell.TH.Syntax)

src/Language/Haskell/TH/Instances.hs:48:26:
    Not in scope: data constructor ‘ClassP’
    Perhaps you meant one of these:
      ‘ClassD’ (imported from Language.Haskell.TH.Syntax),
      ‘ClassI’ (imported from Language.Haskell.TH.Syntax),
      ‘Clause’ (imported from Language.Haskell.TH.Syntax)
    In the Template Haskell quotation [| ClassP n ts |]

src/Language/Haskell/TH/Instances.hs:49:9:
    Not in scope: data constructor ‘EqualP’

src/Language/Haskell/TH/Instances.hs:49:26:
    Not in scope: data constructor ‘EqualP’
    In the Template Haskell quotation [| EqualP t t2 |]
cabal: Error: some packages failed to install:
```

**Comment by ninegua** [comment]
Looks like there is significant incompatibility to the new Template Haskell. I can look into this, but I won't promise an immediate fix because I want the package to work with older GHC too. So for now, I'd suggest you use GHC 7.8.4 for Euterpea.

**Comment by ninegua** [comment]
Should have been fixed by new version 0.1.5.3.
